### ISSUE TITLE
実際に結構シンプルなHTML5の土台を追加する

### ISSUE THREAD

**Issue by ryosuketter** [test-gr/test#2]
Gよろしく

**Comment by ryosuketter** [comment]
'''
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title></title>
<meta charset="utf-8">
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="">

<link rel="shortcut icon" href="">
</head>
<body>



</body>
</html>
'''

**Comment by masuno** [comment]
確認してください
```
<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<title>Page Title</title>
</head>
<body>
</body>
</html>
```

**Comment by masuno** [comment]
html5で #1
実際に結構シンプルなHTML5の土台を追加する #2

**Comment by masuno** [comment]
index.htmlを追加しました #3
